### ISSUE TITLE
AttributeError: 'range' object has no attribute 'remove'

### ISSUE THREAD

**Issue by gijdoul** [ostenbom/dot-to-dot#6]
I receive this error it seem because the code is not up to date 

LineConnector.py", line 54, in greedySolution
    freeList.remove(current)
AttributeError: 'range' object has no attribute 'remove'

I use Python 3

**Comment by gijdoul** [comment]
I fix the error by changing the line 13 on the file LineConnector.py
`self.indexes = range(len(lines) * 2)`
to
 `self.indexes = list(range(len(lines) * 2))`

**Comment by abelparia** [comment]
I fixed line 90 replacing i/2 by i//2 because I got this TypeError: list indices must be integers or slices, not float.

However, I receive another one on line 50 and don't know how to fix it. Can you help?
